#!/bin/bash
set -euxo pipefail

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
THIS="$(readlink -f ${BASH_SOURCE[0]})"

cd ${HERE}

upload () {
    rsync -rpv \
        --exclude="__pycache__" \
        --exclude="*.pkl" \
        --exclude="*.csv" \
        --exclude="*.json" \
        muon zoo:/home/larai002/Zooniverse/repos/muon/
    rsync -rcv \
        muon/scripts/models/decv2/*.csv \
        zoo:/home/larai002/Zooniverse/repos/muon/muon/scripts/models/decv2

    rsync setup.py zoo:/home/larai002/Zooniverse/repos/muon
    rsync muon.env zoo:/home/larai002/Zooniverse/repos/muon

    rsync -rpv \
        --exclude="venv" \
        --exclude="__pycache__" \
        --exclude="*.pkl" \
        --exclude="*.csv" \
        --exclude="*.json" \
        --exclude=".git" \
        ${ZOO}/redec-keras zoo:/home/larai002/Zooniverse/repos
}

desktop () {
    rsync -rv --exclude="__pycache__" --exclude="*.pkl" --exclude="*.csv" --exclude="*.json" muon 10.8.0.1:/home/michael/Documents/Zooniverse/repos/muon/
}

notebook () {
    rsync -rv --exclude="mnt" --include="*.ipynb" zoo:/home/larai002/Zooniverse/repos/muon/notebook/ notebook
}

command=$1
shift
case $command in
    "upload")
        upload
        ;;
    "desktop")
        desktop
        ;;
    "notebook")
        notebook
        ;;
esac
